### ISSUE TITLE
Excluding sourceSets

### ISSUE THREAD

**Issue by shivangshah** [palantir/gradle-jacoco-coverage#12]
Hi, 

Currently it seems like the sourceSets that contain generated classes (from 3rd party) cannot be excluded by packageThreshold. Any idea if this can be supported in the future?

**Comment by uschi2000** [comment]
You can exclude those at the jacoco level rather than at the jacocoCoverage level.

**Comment by shivangshah** [comment]
I actually tried that. Didn't work as expected. Will try again and let you know how it went

**Comment by AndreiD** [comment]
can anyone give an example, I'm having trouble as well

**Comment by uschi2000** [comment]
you can do something like this:

```
jacocoReport {
    // Ignore Immutables-generated code from coverage checks
    afterEvaluate {
        classDirectories = files(classDirectories.files.collect {
            // Exclusion path is project-relative and has a base of compiled classes
            fileTree(dir: it, exclude: '**/Immutable*.class')
        })
    }
}
```
