### ISSUE TITLE
classThreshold and packageThreshold with regex doesn't seem work

### ISSUE THREAD

**Issue by qinfchen** [palantir/gradle-jacoco-coverage#20]
I have a project that needs to include gradle jar in the resource path and jacoco coverage also tests coverage on the classes specified in the jar. But I could not get the jacoco coverage to exclude these classes either through `classThreshold` or `packageThread`

```
packageThreshold 0.0, ~'org/gradle/.*'
or
classThreshold 0.0, ~'org/gradle/.*'
```

**Comment by uschi2000** [comment]
That's very strange. Can you share a repository?

**Comment by richersoon** [comment]
Same here, it doesn't seems to override the `fileThreshold`.

For example:

```
jacocoCoverage {
        fileThreshold 0.8
        packageThreshold 0.0, "foo/app"
}
```

I want to be able to apply code coverage except in `foo/app` package

**Comment by uschi2000** [comment]
@richersoon this is the expected behavior; the different threshold "realms" (file, package, etc) are handled independently, i.e., you cannot override file thresholds with package or project thresholds.

**Comment by uschi2000** [comment]
you can add a second fileTreshold with a regex matching the foo/app path though.

**Comment by uschi2000** [comment]
Closing for now; let me know if this is still relevant.
