### ISSUE TITLE
Test failure on German system (String comparison with double value)

### ISSUE THREAD

**Issue by Riggs333** [palantir/gradle-jacoco-coverage#22]
Running a `gradle clean build` with the current code base on my Linux system lead to a test failure.
# Environment

Ubuntu 15.10
Java 1.8.0_101

Environment variables:

``` bash
$ env | grep LANG
LANG=de_DE.UTF-8
GDM_LANG=de_DE
LANGUAGE=de_DE
```
# Failure of the test

_JacocoCoveragePluginTest. Violations are reported for every realm_

Console output:

<pre>
Condition not satisfied:

result.standardOutput.contains('Violations-are-reported-for-every-realm (0/3 LINE coverage < 1.00000)')
|      |              |
|      |              false
|      The client will now receive all logging from the daemon (pid: 29799). The daemon log file: /home/traude/.gradle/daemon/2.12/daemon-29799.out.log
|      Starting 5th build in daemon [uptime: 11.163 secs, performance: 96%, memory: 45% of 954,7 MB]
|      Executing build with daemon context: DefaultDaemonContext[uid=8057f35b-2f09-4299-9704-d41963008ac0,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/traude/.gradle/daemon,pid=29799,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=DE,-Duser.language=de,-Duser.variant]
|      Starting Build
|      Closing daemon's stdin at end of input.
|      The daemon will no longer process any standard input.
|      Settings evaluated using settings file '/home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/settings.gradle'.
|      Projects loaded. Root project using build file '/home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/build.gradle'.
|      Included projects: [root project 'Violations-are-reported-for-every-realm']
|      Evaluating root project 'Violations-are-reported-for-every-realm' using build file '/home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/build.gradle'.
|      All projects evaluated.
|      Selected primary task 'test' from project :
|      Selected primary task 'checkCoverage' from project :
|      Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test', task ':jacocoTestReport', task ':checkCoverage']
|      Creating In-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/fileHashes.bin: MaxSize{400000}
|      Creating In-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/outputFileStates.bin: MaxSize{3000}
|      Creating In-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/fileSnapshots.bin: MaxSize{10000}
|      Creating In-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/taskArtifacts.bin: MaxSize{2000}
|      :compileJava (Thread[Daemon worker,5,main]) started.
|      :compileJava
|      Invalidating in-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/fileHashes.bin
|      Invalidating in-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/taskArtifacts.bin
|      Invalidating in-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/outputFileStates.bin
|      Invalidating in-memory cache of /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/.gradle/2.12/taskArtifacts/fileSnapshots.bin
|      Executing task ':compileJava' (up-to-date check took 0.003 secs) due to:
|        No history is available.
|      All input files are considered out-of-date for incremental task ':compileJava'.
|      Compiling with JDK Java compiler API.
|      :compileJava (Thread[Daemon worker,5,main]) completed. Took 0.024 secs.
|      :processResources (Thread[Daemon worker,5,main]) started.
|      :processResources
|      file or directory '/home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/src/main/resources', not found
|      Skipping task ':processResources' as it has no source files.
|      :processResources UP-TO-DATE
|      :processResources (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
|      :classes (Thread[Daemon worker,5,main]) started.
|      :classes
|      Skipping task ':classes' as it has no actions.
|      :classes (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
|      :compileTestJava (Thread[Daemon worker,5,main]) started.
|      :compileTestJava
|      Executing task ':compileTestJava' (up-to-date check took 0.009 secs) due to:
|        No history is available.
|      All input files are considered out-of-date for incremental task ':compileTestJava'.
|      Compiling with JDK Java compiler API.
|      :compileTestJava (Thread[Daemon worker,5,main]) completed. Took 0.024 secs.
|      :processTestResources (Thread[Daemon worker,5,main]) started.
|      :processTestResources
|      file or directory '/home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/src/test/resources', not found
|      Skipping task ':processTestResources' as it has no source files.
|      :processTestResources UP-TO-DATE
|      :processTestResources (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
|      :testClasses (Thread[Daemon worker,5,main]) started.
|      :testClasses
|      Skipping task ':testClasses' as it has no actions.
|      :testClasses (Thread[Daemon worker,5,main]) completed. Took 0.001 secs.
|      :test (Thread[Daemon worker,5,main]) started.
|      :test
|      Executing task ':test' (up-to-date check took 0.005 secs) due to:
|        No history is available.
|      Starting process 'Gradle Test Executor 1'. Working directory: /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm Command: /usr/lib/jvm/java-8-oracle/bin/java -Djava.security.manager=jarjar.org.gradle.process.internal.child.BootstrapSecurityManager -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.7.1.201405082137.jar_60i0ht8uxttrgmwja9enyk1re/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,dumponexit=true,output=file,jmx=false -Dfile.encoding=UTF-8 -Duser.country=DE -Duser.language=de -Duser.variant -ea -cp /home/traude/.gradle/caches/2.12/workerMain/gradle-worker.jar jarjar.org.gradle.process.internal.launcher.GradleWorkerMain 'Gradle Test Executor 1'
|      Successfully started process 'Gradle Test Executor 1'
|      Gradle Test Executor 1 started executing tests.
|      Gradle Test Executor 1 finished executing tests.
|      Finished generating test XML results (0.0 secs) into: /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/build/test-results
|      Generating HTML test report...
|      Finished generating test html results (0.003 secs) into: /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/build/reports/tests
|      :test (Thread[Daemon worker,5,main]) completed. Took 1.079 secs.
|      :jacocoTestReport (Thread[Daemon worker,5,main]) started.
|      :jacocoTestReport
|      Executing task ':jacocoTestReport' (up-to-date check took 0.022 secs) due to:
|        No history is available.
|      [ant:jacocoReport] Loading execution data file /home/traude/Projekte/gradle-jacoco-coverage/build/test/com.palantir.jacoco.JacocoCoveragePluginTest/Violations-are-reported-for-every-realm/build/jacoco/test.exec
|      [ant:jacocoReport] Writing bundle 'Violations-are-reported-for-every-realm' with 1 classes
|      :jacocoTestReport (Thread[Daemon worker,5,main]) completed. Took 0.383 secs.
|      :checkCoverage (Thread[Daemon worker,5,main]) started.
|      :checkCoverage
|      Executing task ':checkCoverage' (up-to-date check took 0.0 secs) due to:
|        Task has not declared any outputs.
|      Found the following Jacoco coverage violations
|      HelloWorld.java (0/3 LINE coverage < 1,00000)
|      <b>Violations-are-reported-for-every-realm (0/3 LINE coverage < 1,00000)</b>
|      nebula/hello (0/3 LINE coverage < 1,00000)
|      nebula/hello/HelloWorld (0/3 LINE coverage < 1,00000)
|      :checkCoverage FAILED
|      :checkCoverage (Thread[Daemon worker,5,main]) completed. Took 0.007 secs.
|       
|      BUILD FAILED
|       
|      Total time: 1.625 secs
|      Stopped 0 compiler daemon(s).
nebula.test.functional.internal.toolingapi.ToolingExecutionResult@413765f0

    at com.palantir.jacoco.JacocoCoveragePluginTest.Violations are reported for every realm(JacocoCoveragePluginTest.groovy:124)
</pre>

As you can see the expected text is contained but not with the correct format of the double value `1.00000`. It is the German format `1,00000` where a comma separates the integer from the fractional part.
# Root of failure

I see the root of this in the method `CoverageViolation#toString`:

``` groovy
@Override
public String toString() {
    return String.format("%s (%d/%d %s coverage < %g)", clazz, covered, total, type, threshold)
}
```

It is the use of the placeholder `%g` in the call of `String#format`.
# Workaround

Running the build with the following command works fine on my system:
`LC_ALL=en_US.UTF-8 gradle clean build`
# Proposed solution

I'd suggest to change the test to use the class `CoverageViolation` in the assertion, like that:

``` groovy
def reportViolation = new CoverageViolation('Violations-are-reported-for-every-realm', 0, 1.0, 3, CoverageType.LINE)
assert result.standardOutput.contains(reportViolation.toString())
```

What do you think?

**Comment by uschi2000** [comment]
Moin Thomas. Deine proposed solution sieht gut aus. Willst du einen PR machen?

**Comment by ash211** [comment]
@uschi2000 can this issue be closed now?
