### ISSUE TITLE
Can jacocoFullReport exclude classes?

### ISSUE THREAD

**Issue by dyzhou222** [palantir/gradle-jacoco-coverage#32]
Hello,
I was able to use the following to exclude certain classes from code coverage:

    jacocoTestReport {
            afterEvaluate {
                classDirectories = fileTree(dir: "$buildDir",
                        exclude: ['**/*$*$*.class', '**/pkg1/*.class', '**/pkg2/*.class'])
            }
        }
        
However, my next hurdle is that I need to do the same for the jacocoFullReport task as well, in order to avoid the following error:

Caused by: java.io.FileNotFoundException: ...Foo$anonfun$5.html (No such file or directory)
[16:43:10][Gradle failure report] 	at org.apache.tools.ant.types.resources.FileResource.getInputStream(FileResource.java:217)
[16:43:10][Gradle failure report] 	at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:569)
[16:43:10][Gradle failure report] 	at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
[16:43:10][Gradle failure report] 	at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)        

I have both tried and googled extensively but am not able to get it to work.  Could you please confirm whether jacocoFullReport supports excluding certain classes as well, and if so, how?

Thank you in advance.

**Comment by uschi2000** [comment]
Hi,
We have deprecated this plugin in favour of vanilla support in Gradle (>=3.4). Have you considered migrating over to the official solution?
  R

**Comment by dyzhou222** [comment]
Hi @uschi2000 thanks for the response -- would you give me more info no the 'vanilla support' you spoke of?  I'd really appreciate it if you could give me a sample snippet for how excluding files from report should be done today.  Thanks a lot.

**Comment by uschi2000** [comment]
This one: https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_report_violation_rules

The documentation above has examples.

**Comment by dyzhou222** [comment]
Hi @uschi2000, so my code is as follows:

apply plugin: "jacoco"
        jacoco {
            toolVersion = "0.7.6.201602180812"
        }
        jacocoTestCoverageVerification {
            violationRules {
                rule {
                    excludes = ['pkg1.*', 'pkg2.*']
                }
            }
        }
        check.dependsOn jacocoFullReport
        jacocoFullReport.dependsOn jacocoTestReport
        jacocoTestReport.dependsOn jacocoTestCoverageVerification

but I'm getting:

org.gradle.api.internal.MissingMethodException: Could not find method jacocoTestCoverageVerification() for arguments

What am I missing?  Thanks.

**Comment by uschi2000** [comment]
I haven't come across this error, but have you tried Google? E.g., https://stackoverflow.com/questions/46022885/could-not-find-method-jacocotestcoverageverification suggest you might not have applied the java plugin?

**Comment by dyzhou222** [comment]
Hi @uschi2000 yes gradle version issue thanks.  So is the following code correct for excluding files from report?  It has no effect so far.

``
jacocoTestCoverageVerification {
violationRules {
rule {
excludes = ['pkg1.*', 'pkg2.*']
}
}
}
``

**Comment by uschi2000** [comment]
I haven't used this myself, so I'm afraid I won't be able to assist you, sorry.

**Comment by uschi2000** [comment]
Mind if I close this issue?

**Comment by dyzhou222** [comment]
Hi @uschi2000 sure, you can close the issue, thanks for your help.
